### ISSUE TITLE
Org-mermaid-path not recognized

### ISSUE THREAD

**Issue by qall** [arnm/ob-mermaid#3]
Hello,
I am not a programmer so excuse me if I don't use the right words.

With your config 
`(setq org-mermaid-path "/your-installating-path/node_modules/.bin/mmdc")`
I had the following error:

'ob-mermaid-cli-path is not set'

when evaluating the code block.

However, changing the name of the variable to

`(setq ob-mermaid-cli-path "~/node_modules/.bin/mmdc")`

in my dotfile worked fine.

I don't know if this solve anything, just wanted to point it out.

Cheers

**Comment by arnm** [comment]
Yea, sorry about that I need to update the README

**Comment by qall** [comment]
No problem, thank you for this package, I needed it!
