### ISSUE TITLE
No org-babel-execute function for mermaid!

### ISSUE THREAD

**Issue by RidaAyed** [arnm/ob-mermaid#6]
Hi Alexei @arnm 

You're package is exacly what I'm looking for. Thank you so much for that.

I've encountered spacemacs a few days ago and now need help on the subjected message.

Having the diagram under the cursor and hitting `C-c C-c` results in:

`No org-babel-execute function for mermaid!`

![screenshot](https://i.imgur.com/ZKFB8kD.png)

## Remarks of every window displayed in screenshot above
1. I've added the mermaid path
2. The diagram itself
3. Help saying the mermaid package is installed

Can you point me to a certain direction in order to solve that issue?

**Comment by arnm** [comment]
Maybe have a look at my spacemacs file: https://github.com/arnm/dotfiles/blob/master/dotfiles/emacs/.spacemacs 

ob-mermaid package installation: https://github.com/arnm/dotfiles/blob/master/dotfiles/emacs/.spacemacs#L91
ob-mermaid-cli-path: https://github.com/arnm/dotfiles/blob/master/dotfiles/emacs/.spacemacs#L422

Make sure to sync your .spacemacs configuration on any change with `SPC f e R`

**Comment by arnm** [comment]
I made a spacemacs layer which should work for you. Let me know if you run into any issues

https://github.com/arnm/mermaid-layer
