### ISSUE TITLE
Example in readme is incomplete

### ISSUE THREAD

**Issue by alphapapa** [arnm/ob-mermaid#9]
Hi,

It would be helpful if the readme had a complete example.  Specifically, the `#+BEGIN_SRC` headers are not shown, so the user has to guess whether to add `mermaid` or something else.

**Comment by ksafford** [comment]
I tried the headers: `mermaid` `mmd` and `mmdc` all to no avail. So I'm currently stumped.

**Comment by arnm** [comment]
Yea, the Github processing of the README.org file is not the best. If you view it as raw text you can see the example properly.

This does need to be fixed though, I agree.

**Comment by Flinner** [comment]
can be closed? #18
